### PR TITLE
Fix dict iteration in Python 3

### PR DESCRIPTION
**Pull request by sandrinr**
The custom code in "swigify_ib.i" makes use of "list.iteritems()". That method was renamed to "list.items()" in Python 3. To ensure the custom code works in Python 2.7 and 3.x I added the "six" library as a dependency. It enables us to iterate over lists in Python 2.7 and Python 3.x.

### CODE REVIEW

**Comment by sandrinr** [comment]
BTW: This should solve issue #25.

**Comment by Komnomnomnom** [comment]
Thanks @sandrinr appreciate you taking the time to put together the pull request.

I'd rather not add a dependency on `six` though. Just the changing the two affected lines to `items()` should do fine.

**Comment by Komnomnomnom** [comment]
Closed by c142d2fc995814498007032ba6d91324ff6c6b44

**Comment by sandrinr** [comment]
As far as I understand it swigibpy will not be able to run on Python-2.7 anymore if you just take over the change to list.items(). Since I am not using Python-2 anymore this is acceptable for me.

**Comment by Komnomnomnom** [comment]
Yep in Python 2 `items()` returns a `list` and `iteritems()` returns an `iterator`. In Python 3 `items()` and many other methods (e.g. `range`) were changed to return iterators and their iterator equivalents were removed. Changes these two lines to use `items()` has negligible overhead in Python 2.

**Pull request closed without merging**
